<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/Vectorized_Operations_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Task 1: Initialize Energy Consumption Data

energy_data = np.array([
    [12, 14, 13, 15, 16, 14],
    [10, 11, 12, 13, 14, 12],
    [20, 22, 21, 23, 24, 22],
    [8, 9, 10, 11, 12, 10],
    [15, 16, 17, 18, 19, 17]
])

# Print the array
print("Energy Data (kWh):")
print(energy_data)

# Print shape
print("\nShape of energy data:", energy_data.shape)

Energy Data (kWh):
[[12 14 13 15 16 14]
 [10 11 12 13 14 12]
 [20 22 21 23 24 22]
 [ 8  9 10 11 12 10]
 [15 16 17 18 19 17]]

Shape of energy data: (5, 6)


In [ ]:
# Task 2: Apply Load Adjustment Using Vectorization

adjusted_energy = energy_data * 1.10

print("Adjusted Energy Consumption (+10%):")
print(adjusted_energy)

Adjusted Energy Consumption (+10%):
[[13.2 15.4 14.3 16.5 17.6 15.4]
 [11.  12.1 13.2 14.3 15.4 13.2]
 [22.  24.2 23.1 25.3 26.4 24.2]
 [ 8.8  9.9 11.  12.1 13.2 11. ]
 [16.5 17.6 18.7 19.8 20.9 18.7]]


In [ ]:
# Task 3: Hour-Based Calibration Using Broadcasting

calibration_factors = np.array([1.0, 0.98, 1.02, 1.01, 0.99, 1.03])

calibrated_energy = adjusted_energy * calibration_factors

print("Calibrated Energy Consumption:")
print(calibrated_energy)

Calibrated Energy Consumption:
[[13.2   15.092 14.586 16.665 17.424 15.862]
 [11.    11.858 13.464 14.443 15.246 13.596]
 [22.    23.716 23.562 25.553 26.136 24.926]
 [ 8.8    9.702 11.22  12.221 13.068 11.33 ]
 [16.5   17.248 19.074 19.998 20.691 19.261]]


In [ ]:
# Average energy per machine

avg_energy_per_machine = np.mean(calibrated_energy, axis=1)

print("Average Energy Consumption per Machine:")
print(avg_energy_per_machine)

Average Energy Consumption per Machine:
[15.4715     13.26783333 24.3155     11.05683333 18.79533333]


In [ ]:
# Maximum energy value

max_energy = np.max(calibrated_energy)

print("\nMaximum Energy Consumption in Dataset:")
print(max_energy)


Maximum Energy Consumption in Dataset:
26.136000000000003
